export interface Ingredient {
  id: string;
  name: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  micronutrient?: { name: string; value: string };
  image: string;
}

export interface Category {
  id: string;
  name: string;
  /** 'orbital' uses OrbitalSelect; 'list' uses MultiSelectList */
  selectionMode: 'orbital' | 'list';
  ingredients: Ingredient[];
}

export const categories: Category[] = [
  {
    id: 'base',
    name: 'Base',
    selectionMode: 'orbital',
    ingredients: [
      {
        id: 'plain-greek-yogurt',
        name: 'Plain Greek Yogurt',
        calories: 100,
        protein: 17,
        carbs: 6,
        fat: 1,
        micronutrient: { name: 'Calcium', value: '187mg' },
        image: '/Yogurt/Bowl1.jpg',
      },
      {
        id: 'vanilla-greek-yogurt',
        name: 'Vanilla Greek Yogurt',
        calories: 110,
        protein: 15,
        carbs: 9,
        fat: 1,
        micronutrient: { name: 'Calcium', value: '180mg' },
        image: '/Yogurt/Bowl2a.jpg',
      },
      {
        id: 'vegan-yogurt-coconut',
        name: 'Vegan Yogurt Coconut',
        calories: 180,
        protein: 2,
        carbs: 12,
        fat: 14,
        micronutrient: { name: 'Iron', value: '1.8mg' },
        image: '/Yogurt/Bowl3a.jpg',
      },
      {
        id: 'high-protein-greek-yogurt',
        name: 'High Protein Greek Yogurt 0% Fat',
        calories: 90,
        protein: 20,
        carbs: 5,
        fat: 0,
        micronutrient: { name: 'Protein', value: '20g' },
        image: '/Yogurt/Bowl4a.jpg',
      },
    ],
  },
  {
    id: 'fruit',
    name: 'Fruit',
    selectionMode: 'orbital',
    ingredients: [
      {
        id: 'blueberries',
        name: 'Blueberries',
        calories: 42,
        protein: 1,
        carbs: 11,
        fat: 0,
        micronutrient: { name: 'Vitamin C', value: '14mg' },
        image: '/Yogurt/Bowl4b.jpg',
      },
      {
        id: 'strawberries',
        name: 'Strawberries',
        calories: 32,
        protein: 1,
        carbs: 8,
        fat: 0,
        micronutrient: { name: 'Vitamin C', value: '58mg' },
        image: '/Yogurt/Bowl5b.jpg',
      },
      {
        id: 'banana',
        name: 'Banana',
        calories: 89,
        protein: 1,
        carbs: 23,
        fat: 0,
        micronutrient: { name: 'Potassium', value: '358mg' },
        image: '/Yogurt/Bowl6b.jpg',
      },
      {
        id: 'pineapple',
        name: 'Pineapple',
        calories: 50,
        protein: 1,
        carbs: 13,
        fat: 0,
        micronutrient: { name: 'Vitamin C', value: '47mg' },
        image: '/Yogurt/Bowl7b.jpg',
      },
      {
        id: 'passionfruit',
        name: 'Passionfruit',
        calories: 17,
        protein: 0,
        carbs: 4,
        fat: 0,
        micronutrient: { name: 'Vitamin A', value: '12mcg' },
        image: '/Yogurt/Background1.jpg',
      },
      {
        id: 'papaya',
        name: 'Papaya',
        calories: 43,
        protein: 1,
        carbs: 11,
        fat: 0,
        micronutrient: { name: 'Vitamin C', value: '61mg' },
        image: '/Yogurt/Background2.jpg',
      },
      {
        id: 'mango',
        name: 'Mango',
        calories: 60,
        protein: 1,
        carbs: 15,
        fat: 0,
        micronutrient: { name: 'Vitamin A', value: '54mcg' },
        image: '/Yogurt/Bowl7b.jpg',
      },
    ],
  },
  {
    id: 'nuts-seeds',
    name: 'Nuts & Seeds',
    selectionMode: 'orbital',
    ingredients: [
      {
        id: 'almonds',
        name: 'Almonds',
        calories: 80,
        protein: 3,
        carbs: 3,
        fat: 7,
        micronutrient: { name: 'Vitamin E', value: '3.7mg' },
        image: '/Yogurt/Background3.jpg',
      },
      {
        id: 'pistachios',
        name: 'Pistachios',
        calories: 80,
        protein: 3,
        carbs: 4,
        fat: 6,
        micronutrient: { name: 'Potassium', value: '150mg' },
        image: '/Yogurt/Background4.jpg',
      },
      {
        id: 'cashews',
        name: 'Cashews',
        calories: 87,
        protein: 2,
        carbs: 5,
        fat: 7,
        micronutrient: { name: 'Magnesium', value: '37mg' },
        image: '/Yogurt/Background5.jpg',
      },
      {
        id: 'walnuts',
        name: 'Walnuts',
        calories: 93,
        protein: 2,
        carbs: 2,
        fat: 9,
        micronutrient: { name: 'Omega-3', value: '2.5g' },
        image: '/Yogurt/Background6.jpg',
      },
      {
        id: 'hemp-hearts',
        name: 'Hemp Hearts',
        calories: 55,
        protein: 3,
        carbs: 1,
        fat: 4,
        micronutrient: { name: 'Omega-3', value: '1g' },
        image: '/Yogurt/Background7.jpg',
      },
      {
        id: 'pumpkin-seeds',
        name: 'Pumpkin Seeds',
        calories: 70,
        protein: 3,
        carbs: 2,
        fat: 6,
        micronutrient: { name: 'Magnesium', value: '73mg' },
        image: '/Yogurt/Hands1.jpg',
      },
      {
        id: 'chia-seeds',
        name: 'Chia Seeds',
        calories: 60,
        protein: 2,
        carbs: 5,
        fat: 4,
        micronutrient: { name: 'Fiber', value: '5g' },
        image: '/Yogurt/Hands2.jpg',
      },
      {
        id: 'sunflower-seeds',
        name: 'Sunflower Seeds',
        calories: 74,
        protein: 3,
        carbs: 3,
        fat: 6,
        micronutrient: { name: 'Vitamin E', value: '4.9mg' },
        image: '/Yogurt/Hands3.jpg',
      },
    ],
  },
  {
    id: 'toppings',
    name: 'Toppings',
    selectionMode: 'orbital',
    ingredients: [
      {
        id: 'flax-meal',
        name: 'Flax Meal',
        calories: 37,
        protein: 1,
        carbs: 2,
        fat: 3,
        micronutrient: { name: 'Fiber', value: '2g' },
        image: '/Yogurt/Bowl3b.jpg',
      },
      {
        id: 'house-granola',
        name: 'House Granola',
        calories: 120,
        protein: 3,
        carbs: 18,
        fat: 5,
        micronutrient: { name: 'Iron', value: '2mg' },
        image: '/Yogurt/Bowl5a.jpg',
      },
      {
        id: 'toasted-coconut',
        name: 'Toasted Coconut',
        calories: 70,
        protein: 1,
        carbs: 3,
        fat: 7,
        micronutrient: { name: 'Manganese', value: '0.6mg' },
        image: '/Yogurt/Bowl6a.jpg',
      },
      {
        id: 'cacao-nibs',
        name: 'Cacao Nibs',
        calories: 65,
        protein: 2,
        carbs: 5,
        fat: 5,
        micronutrient: { name: 'Magnesium', value: '40mg' },
        image: '/Yogurt/Bowl7a.jpg',
      },
      {
        id: 'raw-cocoa-powder',
        name: 'Raw Cocoa Powder',
        calories: 25,
        protein: 2,
        carbs: 4,
        fat: 1,
        micronutrient: { name: 'Iron', value: '1.8mg' },
        image: '/Yogurt/Bowl4c.jpg',
      },
      {
        id: 'shredded-coconut',
        name: 'Shredded Coconut',
        calories: 70,
        protein: 1,
        carbs: 3,
        fat: 7,
        micronutrient: { name: 'Manganese', value: '0.6mg' },
        image: '/Yogurt/Bowl2b.jpg',
      },
      {
        id: 'bee-pollen',
        name: 'Bee Pollen',
        calories: 23,
        protein: 1,
        carbs: 4,
        fat: 0,
        micronutrient: { name: 'Antioxidants', value: 'High' },
        image: '/Yogurt/Hands4.jpg',
      },
      {
        id: 'goji-berries',
        name: 'Goji Berries',
        calories: 50,
        protein: 2,
        carbs: 11,
        fat: 0,
        micronutrient: { name: 'Vitamin A', value: '140mcg' },
        image: '/Yogurt/Bowl4b.jpg',
      },
    ],
  },
  {
    id: 'sauces',
    name: 'Sauces',
    selectionMode: 'orbital',
    ingredients: [
      {
        id: 'raw-honey',
        name: 'Raw Honey',
        calories: 64,
        protein: 0,
        carbs: 17,
        fat: 0,
        micronutrient: { name: 'Antioxidants', value: 'Moderate' },
        image: '/Yogurt/Background7.jpg',
      },
      {
        id: 'maple-syrup',
        name: 'Maple Syrup',
        calories: 52,
        protein: 0,
        carbs: 13,
        fat: 0,
        micronutrient: { name: 'Manganese', value: '0.5mg' },
        image: '/Yogurt/Hands1.jpg',
      },
      {
        id: 'peanut-butter-mousse',
        name: 'Peanut Butter Mousse',
        calories: 95,
        protein: 4,
        carbs: 3,
        fat: 8,
        micronutrient: { name: 'Magnesium', value: '25mg' },
        image: '/Yogurt/Hands2.jpg',
      },
    ],
  },
  {
    id: 'enhancers',
    name: 'Enhancers',
    selectionMode: 'list',
    ingredients: [
      {
        id: 'whey-protein-isolate',
        name: 'Whey Protein Isolate',
        calories: 120,
        protein: 25,
        carbs: 2,
        fat: 1,
        micronutrient: { name: 'BCAAs', value: '5.5g' },
        image: '/Yogurt/Bowl1.jpg',
      },
      {
        id: 'mct-oil',
        name: 'MCT Oil',
        calories: 120,
        protein: 0,
        carbs: 0,
        fat: 14,
        micronutrient: { name: 'Medium Chain Fats', value: '14g' },
        image: '/Yogurt/Bowl1.jpg',
      },
      {
        id: 'lions-mane',
        name: "Lion's Mane",
        calories: 5,
        protein: 0,
        carbs: 1,
        fat: 0,
        micronutrient: { name: 'Beta-glucans', value: 'High' },
        image: '/Yogurt/Bowl1.jpg',
      },
      {
        id: 'flax-oil',
        name: 'Flax Oil',
        calories: 120,
        protein: 0,
        carbs: 0,
        fat: 14,
        micronutrient: { name: 'Omega-3', value: '7g' },
        image: '/Yogurt/Bowl1.jpg',
      },
      {
        id: 'turmeric-black-pepper',
        name: 'Turmeric + Black Pepper',
        calories: 8,
        protein: 0,
        carbs: 1,
        fat: 0,
        micronutrient: { name: 'Curcumin', value: 'High' },
        image: '/Yogurt/Bowl1.jpg',
      },
      {
        id: 'spirulina',
        name: 'Spirulina',
        calories: 20,
        protein: 4,
        carbs: 2,
        fat: 0,
        micronutrient: { name: 'Iron', value: '2mg' },
        image: '/Yogurt/Bowl1.jpg',
      },
      {
        id: 'l-glutamine',
        name: 'L-Glutamine',
        calories: 20,
        protein: 5,
        carbs: 0,
        fat: 0,
        micronutrient: { name: 'Amino Acids', value: '5g' },
        image: '/Yogurt/Bowl1.jpg',
      },
      {
        id: 'collagen-peptides',
        name: 'Collagen Peptides',
        calories: 35,
        protein: 9,
        carbs: 0,
        fat: 0,
        micronutrient: { name: 'Glycine', value: '2.1g' },
        image: '/Yogurt/Bowl1.jpg',
      },
      {
        id: 'creatine-monohydrate',
        name: 'Creatine Monohydrate',
        calories: 15,
        protein: 0,
        carbs: 0,
        fat: 0,
        micronutrient: { name: 'Creatine', value: '5g' },
        image: '/Yogurt/Bowl1.jpg',
      },
      {
        id: 'greens-powder',
        name: 'Greens Powder',
        calories: 25,
        protein: 1,
        carbs: 4,
        fat: 0,
        micronutrient: { name: 'Vitamin K', value: 'High' },
        image: '/Yogurt/Bowl1.jpg',
      },
      {
        id: 'nutritional-yeast',
        name: 'Nutritional Yeast',
        calories: 45,
        protein: 8,
        carbs: 5,
        fat: 0,
        micronutrient: { name: 'B12', value: '2.4mcg' },
        image: '/Yogurt/Bowl1.jpg',
      },
      {
        id: 'ashwagandha',
        name: 'Ashwagandha',
        calories: 5,
        protein: 0,
        carbs: 1,
        fat: 0,
        micronutrient: { name: 'Withanolides', value: 'High' },
        image: '/Yogurt/Bowl1.jpg',
      },
      {
        id: 'matcha',
        name: 'Matcha',
        calories: 10,
        protein: 1,
        carbs: 1,
        fat: 0,
        micronutrient: { name: 'L-theanine', value: 'High' },
        image: '/Yogurt/Bowl1.jpg',
      },
      {
        id: 'maca-powder',
        name: 'Maca Powder',
        calories: 20,
        protein: 1,
        carbs: 4,
        fat: 0,
        micronutrient: { name: 'Vitamin C', value: '3mg' },
        image: '/Yogurt/Bowl1.jpg',
      },
      {
        id: 'evoo',
        name: 'EVOO',
        calories: 120,
        protein: 0,
        carbs: 0,
        fat: 14,
        micronutrient: { name: 'Polyphenols', value: 'High' },
        image: '/Yogurt/Bowl1.jpg',
      },
    ],
  },
];

export const dailyGoals = {
  calories: 2000,
  protein: 50,
  carbs: 300,
  fat: 65,
};
