export interface Ingredient {
  id: string;
  name: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  micronutrient?: { name: string; value: string };
  image: string;
}

export interface Category {
  id: string;
  name: string;
  ingredients: Ingredient[];
}

export const categories: Category[] = [
  {
    id: 'base',
    name: 'Base',
    ingredients: [
      {
        id: 'greek-yogurt',
        name: 'Greek Yogurt',
        calories: 100,
        protein: 17,
        carbs: 6,
        fat: 1,
        micronutrient: { name: 'Calcium', value: '187mg' },
        image: '/Yogurt/Bowl1.jpg',
      },
      {
        id: 'coconut-yogurt',
        name: 'Coconut Yogurt',
        calories: 180,
        protein: 2,
        carbs: 12,
        fat: 14,
        micronutrient: { name: 'Iron', value: '1.8mg' },
        image: '/Yogurt/Bowl2a.jpg',
      },
      {
        id: 'acai-base',
        name: 'Acai Base',
        calories: 70,
        protein: 1,
        carbs: 4,
        fat: 5,
        micronutrient: { name: 'Antioxidants', value: 'High' },
        image: '/Yogurt/Bowl3a.jpg',
      },
      {
        id: 'oat-base',
        name: 'Oat Base',
        calories: 150,
        protein: 5,
        carbs: 27,
        fat: 3,
        micronutrient: { name: 'Fiber', value: '4g' },
        image: '/Yogurt/Bowl4a.jpg',
      },
    ],
  },
  {
    id: 'protein',
    name: 'Protein',
    ingredients: [
      {
        id: 'almond-butter',
        name: 'Almond Butter',
        calories: 98,
        protein: 3,
        carbs: 3,
        fat: 9,
        micronutrient: { name: 'Vitamin E', value: '4mg' },
        image: '/Yogurt/Bowl5a.jpg',
      },
      {
        id: 'peanut-butter',
        name: 'Peanut Butter',
        calories: 95,
        protein: 4,
        carbs: 3,
        fat: 8,
        micronutrient: { name: 'Magnesium', value: '25mg' },
        image: '/Yogurt/Bowl6a.jpg',
      },
      {
        id: 'hemp-seeds',
        name: 'Hemp Seeds',
        calories: 55,
        protein: 3,
        carbs: 1,
        fat: 4,
        micronutrient: { name: 'Omega-3', value: '1g' },
        image: '/Yogurt/Bowl7a.jpg',
      },
      {
        id: 'chia-seeds',
        name: 'Chia Seeds',
        calories: 60,
        protein: 2,
        carbs: 5,
        fat: 4,
        micronutrient: { name: 'Fiber', value: '5g' },
        image: '/Yogurt/Bowl2b.jpg',
      },
      {
        id: 'whey-protein',
        name: 'Whey Protein',
        calories: 120,
        protein: 24,
        carbs: 3,
        fat: 1,
        micronutrient: { name: 'BCAAs', value: '5.5g' },
        image: '/Yogurt/Bowl3b.jpg',
      },
    ],
  },
  {
    id: 'fruits',
    name: 'Fruits',
    ingredients: [
      {
        id: 'blueberries',
        name: 'Blueberries',
        calories: 42,
        protein: 1,
        carbs: 11,
        fat: 0,
        micronutrient: { name: 'Vitamin C', value: '14mg' },
        image: '/Yogurt/Bowl4b.jpg',
      },
      {
        id: 'strawberries',
        name: 'Strawberries',
        calories: 32,
        protein: 1,
        carbs: 8,
        fat: 0,
        micronutrient: { name: 'Vitamin C', value: '58mg' },
        image: '/Yogurt/Bowl5b.jpg',
      },
      {
        id: 'banana',
        name: 'Banana',
        calories: 89,
        protein: 1,
        carbs: 23,
        fat: 0,
        micronutrient: { name: 'Potassium', value: '358mg' },
        image: '/Yogurt/Bowl6b.jpg',
      },
      {
        id: 'mango',
        name: 'Mango',
        calories: 60,
        protein: 1,
        carbs: 15,
        fat: 0,
        micronutrient: { name: 'Vitamin A', value: '54mcg' },
        image: '/Yogurt/Bowl7b.jpg',
      },
      {
        id: 'raspberries',
        name: 'Raspberries',
        calories: 32,
        protein: 1,
        carbs: 7,
        fat: 0,
        micronutrient: { name: 'Fiber', value: '4g' },
        image: '/Yogurt/Background1.jpg',
      },
    ],
  },
  {
    id: 'toppings',
    name: 'Toppings',
    ingredients: [
      {
        id: 'granola',
        name: 'Granola',
        calories: 120,
        protein: 3,
        carbs: 18,
        fat: 5,
        micronutrient: { name: 'Iron', value: '2mg' },
        image: '/Yogurt/Background2.jpg',
      },
      {
        id: 'coconut-flakes',
        name: 'Coconut Flakes',
        calories: 70,
        protein: 1,
        carbs: 3,
        fat: 7,
        micronutrient: { name: 'Manganese', value: '0.6mg' },
        image: '/Yogurt/Background3.jpg',
      },
      {
        id: 'cacao-nibs',
        name: 'Cacao Nibs',
        calories: 65,
        protein: 2,
        carbs: 5,
        fat: 5,
        micronutrient: { name: 'Magnesium', value: '40mg' },
        image: '/Yogurt/Background4.jpg',
      },
      {
        id: 'goji-berries',
        name: 'Goji Berries',
        calories: 50,
        protein: 2,
        carbs: 11,
        fat: 0,
        micronutrient: { name: 'Vitamin A', value: '140mcg' },
        image: '/Yogurt/Background5.jpg',
      },
      {
        id: 'sliced-almonds',
        name: 'Sliced Almonds',
        calories: 80,
        protein: 3,
        carbs: 3,
        fat: 7,
        micronutrient: { name: 'Vitamin E', value: '3.7mg' },
        image: '/Yogurt/Background6.jpg',
      },
    ],
  },
  {
    id: 'drizzles',
    name: 'Drizzles',
    ingredients: [
      {
        id: 'honey',
        name: 'Raw Honey',
        calories: 64,
        protein: 0,
        carbs: 17,
        fat: 0,
        micronutrient: { name: 'Antioxidants', value: 'Moderate' },
        image: '/Yogurt/Background7.jpg',
      },
      {
        id: 'maple-syrup',
        name: 'Maple Syrup',
        calories: 52,
        protein: 0,
        carbs: 13,
        fat: 0,
        micronutrient: { name: 'Manganese', value: '0.5mg' },
        image: '/Yogurt/Hands1.jpg',
      },
      {
        id: 'agave',
        name: 'Agave Nectar',
        calories: 60,
        protein: 0,
        carbs: 16,
        fat: 0,
        micronutrient: { name: 'Calcium', value: '1mg' },
        image: '/Yogurt/Hands2.jpg',
      },
      {
        id: 'dark-chocolate',
        name: 'Dark Chocolate',
        calories: 45,
        protein: 1,
        carbs: 4,
        fat: 3,
        micronutrient: { name: 'Iron', value: '1.2mg' },
        image: '/Yogurt/Hands3.jpg',
      },
    ],
  },
];

export const dailyGoals = {
  calories: 2000,
  protein: 50,
  carbs: 300,
  fat: 65,
};
